[package]
name = "news-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
serde = { version = "1.0.217", features = ["derive"] }
dotenv = "0.15.0"
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.42.0", features = ["full"] }